// Generated by gencpp from file idxpendant/SwitchRequestRequest.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHREQUESTREQUEST_H
#define IDXPENDANT_MESSAGE_SWITCHREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace idxpendant
{
template <class ContainerAllocator>
struct SwitchRequestRequest_
{
  typedef SwitchRequestRequest_<ContainerAllocator> Type;

  SwitchRequestRequest_()
    : switch_no(0)
    , switch_name()  {
    }
  SwitchRequestRequest_(const ContainerAllocator& _alloc)
    : switch_no(0)
    , switch_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _switch_no_type;
  _switch_no_type switch_no;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _switch_name_type;
  _switch_name_type switch_name;




  typedef boost::shared_ptr< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchRequestRequest_

typedef ::idxpendant::SwitchRequestRequest_<std::allocator<void> > SwitchRequestRequest;

typedef boost::shared_ptr< ::idxpendant::SwitchRequestRequest > SwitchRequestRequestPtr;
typedef boost::shared_ptr< ::idxpendant::SwitchRequestRequest const> SwitchRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::idxpendant::SwitchRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace idxpendant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'idxpendant': ['/home/pi/ros_idx6dof/src/idxpendant/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa12f830fb6e2fa5f41c1372ab0fc350";
  }

  static const char* value(const ::idxpendant::SwitchRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa12f830fb6e2fa5ULL;
  static const uint64_t static_value2 = 0xf41c1372ab0fc350ULL;
};

template<class ContainerAllocator>
struct DataType< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "idxpendant/SwitchRequestRequest";
  }

  static const char* value(const ::idxpendant::SwitchRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 switch_no\n\
string switch_name\n\
";
  }

  static const char* value(const ::idxpendant::SwitchRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.switch_no);
      stream.next(m.switch_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwitchRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::idxpendant::SwitchRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::idxpendant::SwitchRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "switch_no: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_no);
    s << indent << "switch_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.switch_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHREQUESTREQUEST_H
