// Generated by gencpp from file idxpendant/SwitchsSrvRequest.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHSSRVREQUEST_H
#define IDXPENDANT_MESSAGE_SWITCHSSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace idxpendant
{
template <class ContainerAllocator>
struct SwitchsSrvRequest_
{
  typedef SwitchsSrvRequest_<ContainerAllocator> Type;

  SwitchsSrvRequest_()
    {
    }
  SwitchsSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchsSrvRequest_

typedef ::idxpendant::SwitchsSrvRequest_<std::allocator<void> > SwitchsSrvRequest;

typedef boost::shared_ptr< ::idxpendant::SwitchsSrvRequest > SwitchsSrvRequestPtr;
typedef boost::shared_ptr< ::idxpendant::SwitchsSrvRequest const> SwitchsSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace idxpendant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'idxpendant': ['/home/pi/ros_idx6dof/src/idxpendant/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::idxpendant::SwitchsSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "idxpendant/SwitchsSrvRequest";
  }

  static const char* value(const ::idxpendant::SwitchsSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::idxpendant::SwitchsSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwitchsSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::idxpendant::SwitchsSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::idxpendant::SwitchsSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHSSRVREQUEST_H
