// Generated by gencpp from file idxpendant/SwitchsSrv.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHSSRV_H
#define IDXPENDANT_MESSAGE_SWITCHSSRV_H

#include <ros/service_traits.h>


#include <idxpendant/SwitchsSrvRequest.h>
#include <idxpendant/SwitchsSrvResponse.h>


namespace idxpendant
{

struct SwitchsSrv
{

typedef SwitchsSrvRequest Request;
typedef SwitchsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchsSrv
} // namespace idxpendant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::idxpendant::SwitchsSrv > {
  static const char* value()
  {
    return "fdfeb5028b697838b970222e35ad759c";
  }

  static const char* value(const ::idxpendant::SwitchsSrv&) { return value(); }
};

template<>
struct DataType< ::idxpendant::SwitchsSrv > {
  static const char* value()
  {
    return "idxpendant/SwitchsSrv";
  }

  static const char* value(const ::idxpendant::SwitchsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::idxpendant::SwitchsSrvRequest> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchsSrv > 
template<>
struct MD5Sum< ::idxpendant::SwitchsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchsSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchsSrvRequest> should match 
// service_traits::DataType< ::idxpendant::SwitchsSrv > 
template<>
struct DataType< ::idxpendant::SwitchsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchsSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::idxpendant::SwitchsSrvResponse> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchsSrv > 
template<>
struct MD5Sum< ::idxpendant::SwitchsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchsSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchsSrvResponse> should match 
// service_traits::DataType< ::idxpendant::SwitchsSrv > 
template<>
struct DataType< ::idxpendant::SwitchsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchsSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHSSRV_H
