// Generated by gencpp from file idxpendant/SwitchesSrv.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHESSRV_H
#define IDXPENDANT_MESSAGE_SWITCHESSRV_H

#include <ros/service_traits.h>


#include <idxpendant/SwitchesSrvRequest.h>
#include <idxpendant/SwitchesSrvResponse.h>


namespace idxpendant
{

struct SwitchesSrv
{

typedef SwitchesSrvRequest Request;
typedef SwitchesSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchesSrv
} // namespace idxpendant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::idxpendant::SwitchesSrv > {
  static const char* value()
  {
    return "fdfeb5028b697838b970222e35ad759c";
  }

  static const char* value(const ::idxpendant::SwitchesSrv&) { return value(); }
};

template<>
struct DataType< ::idxpendant::SwitchesSrv > {
  static const char* value()
  {
    return "idxpendant/SwitchesSrv";
  }

  static const char* value(const ::idxpendant::SwitchesSrv&) { return value(); }
};


// service_traits::MD5Sum< ::idxpendant::SwitchesSrvRequest> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchesSrv > 
template<>
struct MD5Sum< ::idxpendant::SwitchesSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchesSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchesSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchesSrvRequest> should match 
// service_traits::DataType< ::idxpendant::SwitchesSrv > 
template<>
struct DataType< ::idxpendant::SwitchesSrvRequest>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchesSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchesSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::idxpendant::SwitchesSrvResponse> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchesSrv > 
template<>
struct MD5Sum< ::idxpendant::SwitchesSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchesSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchesSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchesSrvResponse> should match 
// service_traits::DataType< ::idxpendant::SwitchesSrv > 
template<>
struct DataType< ::idxpendant::SwitchesSrvResponse>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchesSrv >::value();
  }
  static const char* value(const ::idxpendant::SwitchesSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHESSRV_H
