// Generated by gencpp from file idxpendant/SwitchRequest.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHREQUEST_H
#define IDXPENDANT_MESSAGE_SWITCHREQUEST_H

#include <ros/service_traits.h>


#include <idxpendant/SwitchRequestRequest.h>
#include <idxpendant/SwitchRequestResponse.h>


namespace idxpendant
{

struct SwitchRequest
{

typedef SwitchRequestRequest Request;
typedef SwitchRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchRequest
} // namespace idxpendant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::idxpendant::SwitchRequest > {
  static const char* value()
  {
    return "12242c3da59534fae1a5eda4f02b556d";
  }

  static const char* value(const ::idxpendant::SwitchRequest&) { return value(); }
};

template<>
struct DataType< ::idxpendant::SwitchRequest > {
  static const char* value()
  {
    return "idxpendant/SwitchRequest";
  }

  static const char* value(const ::idxpendant::SwitchRequest&) { return value(); }
};


// service_traits::MD5Sum< ::idxpendant::SwitchRequestRequest> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchRequest > 
template<>
struct MD5Sum< ::idxpendant::SwitchRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchRequest >::value();
  }
  static const char* value(const ::idxpendant::SwitchRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchRequestRequest> should match 
// service_traits::DataType< ::idxpendant::SwitchRequest > 
template<>
struct DataType< ::idxpendant::SwitchRequestRequest>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchRequest >::value();
  }
  static const char* value(const ::idxpendant::SwitchRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::idxpendant::SwitchRequestResponse> should match 
// service_traits::MD5Sum< ::idxpendant::SwitchRequest > 
template<>
struct MD5Sum< ::idxpendant::SwitchRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::idxpendant::SwitchRequest >::value();
  }
  static const char* value(const ::idxpendant::SwitchRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::idxpendant::SwitchRequestResponse> should match 
// service_traits::DataType< ::idxpendant::SwitchRequest > 
template<>
struct DataType< ::idxpendant::SwitchRequestResponse>
{
  static const char* value()
  {
    return DataType< ::idxpendant::SwitchRequest >::value();
  }
  static const char* value(const ::idxpendant::SwitchRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHREQUEST_H
