// Generated by gencpp from file idxpendant/SwitchPos.msg
// DO NOT EDIT!


#ifndef IDXPENDANT_MESSAGE_SWITCHPOS_H
#define IDXPENDANT_MESSAGE_SWITCHPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace idxpendant
{
template <class ContainerAllocator>
struct SwitchPos_
{
  typedef SwitchPos_<ContainerAllocator> Type;

  SwitchPos_()
    : time()
    , switch_no(0)
    , switch_pos(0)
    , switch_name()  {
    }
  SwitchPos_(const ContainerAllocator& _alloc)
    : time()
    , switch_no(0)
    , switch_pos(0)
    , switch_name(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _time_type;
  _time_type time;

   typedef uint8_t _switch_no_type;
  _switch_no_type switch_no;

   typedef int8_t _switch_pos_type;
  _switch_pos_type switch_pos;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _switch_name_type;
  _switch_name_type switch_name;




  typedef boost::shared_ptr< ::idxpendant::SwitchPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::idxpendant::SwitchPos_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchPos_

typedef ::idxpendant::SwitchPos_<std::allocator<void> > SwitchPos;

typedef boost::shared_ptr< ::idxpendant::SwitchPos > SwitchPosPtr;
typedef boost::shared_ptr< ::idxpendant::SwitchPos const> SwitchPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::idxpendant::SwitchPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::idxpendant::SwitchPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace idxpendant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'idxpendant': ['/home/eric/ros_idx6dof/src/idxpendant/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::idxpendant::SwitchPos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::idxpendant::SwitchPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::idxpendant::SwitchPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::idxpendant::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d256e445299745010b61ca2b82e5e4a";
  }

  static const char* value(const ::idxpendant::SwitchPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d256e4452997450ULL;
  static const uint64_t static_value2 = 0x10b61ca2b82e5e4aULL;
};

template<class ContainerAllocator>
struct DataType< ::idxpendant::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "idxpendant/SwitchPos";
  }

  static const char* value(const ::idxpendant::SwitchPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::idxpendant::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
time time\n\
uint8 switch_no\n\
int8 switch_pos\n\
string switch_name\n\
";
  }

  static const char* value(const ::idxpendant::SwitchPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::idxpendant::SwitchPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.switch_no);
      stream.next(m.switch_pos);
      stream.next(m.switch_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwitchPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::idxpendant::SwitchPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::idxpendant::SwitchPos_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
    s << indent << "switch_no: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.switch_no);
    s << indent << "switch_pos: ";
    Printer<int8_t>::stream(s, indent + "  ", v.switch_pos);
    s << indent << "switch_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.switch_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IDXPENDANT_MESSAGE_SWITCHPOS_H
