(cl:defpackage idxpendant-srv
  (:use )
  (:export
   "SWITCHESSRV"
   "<SWITCHESSRV-REQUEST>"
   "SWITCHESSRV-REQUEST"
   "<SWITCHESSRV-RESPONSE>"
   "SWITCHESSRV-RESPONSE"
   "SWITCHSRV"
   "<SWITCHSRV-REQUEST>"
   "SWITCHSRV-REQUEST"
   "<SWITCHSRV-RESPONSE>"
   "SWITCHSRV-RESPONSE"
  ))

