// Generated by gencpp from file arm/Command.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_COMMAND_H
#define ARM_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : cmd(0)
    , params()  {
    }
  Command_(const ContainerAllocator& _alloc)
    : cmd(0)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _params_type;
  _params_type params;




  typedef boost::shared_ptr< ::arm::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::arm::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::arm::Command > CommandPtr;
typedef boost::shared_ptr< ::arm::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm': ['/home/ubuntu/ros_idx6dof/src/arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::Command_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac224fe040657a122ab633b7a19a6e0a";
  }

  static const char* value(const ::arm::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac224fe040657a12ULL;
  static const uint64_t static_value2 = 0x2ab633b7a19a6e0aULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/Command";
  }

  static const char* value(const ::arm::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 cmd\n\
int32[] params\n\
\n\
";
  }

  static const char* value(const ::arm::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::Command_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_COMMAND_H
