// Generated by gencpp from file arm/IKServiceResponse.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_IKSERVICERESPONSE_H
#define ARM_MESSAGE_IKSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm
{
template <class ContainerAllocator>
struct IKServiceResponse_
{
  typedef IKServiceResponse_<ContainerAllocator> Type;

  IKServiceResponse_()
    : jointPos()  {
    }
  IKServiceResponse_(const ContainerAllocator& _alloc)
    : jointPos(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _jointPos_type;
  _jointPos_type jointPos;




  typedef boost::shared_ptr< ::arm::IKServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::IKServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IKServiceResponse_

typedef ::arm::IKServiceResponse_<std::allocator<void> > IKServiceResponse;

typedef boost::shared_ptr< ::arm::IKServiceResponse > IKServiceResponsePtr;
typedef boost::shared_ptr< ::arm::IKServiceResponse const> IKServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::IKServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::IKServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm': ['/home/drew/ros_idx6dof/src/arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm::IKServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::IKServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::IKServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::IKServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::IKServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::IKServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::IKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58ac670cd5282058b35f9d78ccf3fc5d";
  }

  static const char* value(const ::arm::IKServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58ac670cd5282058ULL;
  static const uint64_t static_value2 = 0xb35f9d78ccf3fc5dULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::IKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/IKServiceResponse";
  }

  static const char* value(const ::arm::IKServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::IKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] jointPos\n\
\n\
";
  }

  static const char* value(const ::arm::IKServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::IKServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jointPos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IKServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::IKServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::IKServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "jointPos[]" << std::endl;
    for (size_t i = 0; i < v.jointPos.size(); ++i)
    {
      s << indent << "  jointPos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.jointPos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_IKSERVICERESPONSE_H
