// Generated by gencpp from file arm/IKService.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_IKSERVICE_H
#define ARM_MESSAGE_IKSERVICE_H

#include <ros/service_traits.h>


#include <arm/IKServiceRequest.h>
#include <arm/IKServiceResponse.h>


namespace arm
{

struct IKService
{

typedef IKServiceRequest Request;
typedef IKServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IKService
} // namespace arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm::IKService > {
  static const char* value()
  {
    return "0811aef5e9050eb25cba782a9faf98fb";
  }

  static const char* value(const ::arm::IKService&) { return value(); }
};

template<>
struct DataType< ::arm::IKService > {
  static const char* value()
  {
    return "arm/IKService";
  }

  static const char* value(const ::arm::IKService&) { return value(); }
};


// service_traits::MD5Sum< ::arm::IKServiceRequest> should match 
// service_traits::MD5Sum< ::arm::IKService > 
template<>
struct MD5Sum< ::arm::IKServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm::IKService >::value();
  }
  static const char* value(const ::arm::IKServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::IKServiceRequest> should match 
// service_traits::DataType< ::arm::IKService > 
template<>
struct DataType< ::arm::IKServiceRequest>
{
  static const char* value()
  {
    return DataType< ::arm::IKService >::value();
  }
  static const char* value(const ::arm::IKServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm::IKServiceResponse> should match 
// service_traits::MD5Sum< ::arm::IKService > 
template<>
struct MD5Sum< ::arm::IKServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm::IKService >::value();
  }
  static const char* value(const ::arm::IKServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm::IKServiceResponse> should match 
// service_traits::DataType< ::arm::IKService > 
template<>
struct DataType< ::arm::IKServiceResponse>
{
  static const char* value()
  {
    return DataType< ::arm::IKService >::value();
  }
  static const char* value(const ::arm::IKServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_MESSAGE_IKSERVICE_H
