// Generated by gencpp from file arm/SwitchPos.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_SWITCHPOS_H
#define ARM_MESSAGE_SWITCHPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm
{
template <class ContainerAllocator>
struct SwitchPos_
{
  typedef SwitchPos_<ContainerAllocator> Type;

  SwitchPos_()
    : pos(0)  {
    }
  SwitchPos_(const ContainerAllocator& _alloc)
    : pos(0)  {
  (void)_alloc;
    }



   typedef int8_t _pos_type;
  _pos_type pos;


    enum { UP = 1 };
     enum { NEUTRAL = 0 };
     enum { DOWN = -1 };
 

  typedef boost::shared_ptr< ::arm::SwitchPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::SwitchPos_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchPos_

typedef ::arm::SwitchPos_<std::allocator<void> > SwitchPos;

typedef boost::shared_ptr< ::arm::SwitchPos > SwitchPosPtr;
typedef boost::shared_ptr< ::arm::SwitchPos const> SwitchPosConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::SwitchPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::SwitchPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm': ['/home/ubuntu/ros_idx6dof/src/arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm::SwitchPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::SwitchPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::SwitchPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::SwitchPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::SwitchPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::SwitchPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "618967a4b6ca1e2301a98e484144452b";
  }

  static const char* value(const ::arm::SwitchPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x618967a4b6ca1e23ULL;
  static const uint64_t static_value2 = 0x01a98e484144452bULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/SwitchPos";
  }

  static const char* value(const ::arm::SwitchPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::SwitchPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 UP=1\n\
int8 NEUTRAL=0\n\
int8 DOWN=-1\n\
int8 pos\n\
";
  }

  static const char* value(const ::arm::SwitchPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::SwitchPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwitchPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::SwitchPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::SwitchPos_<ContainerAllocator>& v)
  {
    s << indent << "pos: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_SWITCHPOS_H
