// Generated by gencpp from file arm/Switches.msg
// DO NOT EDIT!


#ifndef ARM_MESSAGE_SWITCHES_H
#define ARM_MESSAGE_SWITCHES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <arm/SwitchPos.h>

namespace arm
{
template <class ContainerAllocator>
struct Switches_
{
  typedef Switches_<ContainerAllocator> Type;

  Switches_()
    : positions()  {
    }
  Switches_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::arm::SwitchPos_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::arm::SwitchPos_<ContainerAllocator> >::other >  _positions_type;
  _positions_type positions;




  typedef boost::shared_ptr< ::arm::Switches_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm::Switches_<ContainerAllocator> const> ConstPtr;

}; // struct Switches_

typedef ::arm::Switches_<std::allocator<void> > Switches;

typedef boost::shared_ptr< ::arm::Switches > SwitchesPtr;
typedef boost::shared_ptr< ::arm::Switches const> SwitchesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm::Switches_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm::Switches_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'arm': ['/home/ubuntu/ros_idx6dof/src/arm/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm::Switches_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm::Switches_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::Switches_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm::Switches_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::Switches_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm::Switches_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm::Switches_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72336361b4058bc9c050bf84bb606c9f";
  }

  static const char* value(const ::arm::Switches_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72336361b4058bc9ULL;
  static const uint64_t static_value2 = 0xc050bf84bb606c9fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm::Switches_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/Switches";
  }

  static const char* value(const ::arm::Switches_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm::Switches_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm/SwitchPos[] positions\n\
\n\
================================================================================\n\
MSG: arm/SwitchPos\n\
int8 UP=1\n\
int8 NEUTRAL=0\n\
int8 DOWN=-1\n\
int8 pos\n\
";
  }

  static const char* value(const ::arm::Switches_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm::Switches_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Switches_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm::Switches_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm::Switches_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::arm::SwitchPos_<ContainerAllocator> >::stream(s, indent + "    ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_MESSAGE_SWITCHES_H
